- name: JCasC installation
  hosts: all
#  gather_facts: false
  become: yes
  tasks:
    - name: Copy JCasC to remote
      copy:
        src: ./JCasC
        dest: "/home/{{ ansible_user }}"

    - name: Ensures {{ jenkins_home }}/jenkins_conf dir exists
      file:
        path: "{{ item }}"
        mode: 0770
        group: "{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        recurse: true
        state: directory
      with_items:
        - "{{ jenkins_home }}"
        - "{{ jenkins_home }}/jenkins_conf"

    - name: Copy conf to remote
      copy:
        src: ./JCasC/master/jenkins.yaml
        dest: "{{ jenkins_home }}/jenkins_conf/jenkins.yaml"
