- name: JCasC installation
  hosts: all
  gather_facts: false
  become: no
  tasks:
    - name: Copy JCasC to remote
      copy:
        src: ./JCasC
        dest: /home/{{ ansible_user }}/

    - name: Ensures {{project_root}}/conf dir exists
      file:
        path: /home/{{ ansible_user }}/jenkins_home/jenkins_conf
        mode: 0777
        state: directory

    - name: Copy conf to remote
      copy:
        src: ./JCasC/master/jenkins.yaml
        dest: /home/{{ ansible_user }}/jenkins_home/jenkins_conf/jenkins.yaml
