pipeline {
  agent any

    stages {
        stage('Prepare') {
            steps {
                sh 'echo $CASC_REPO'
                sh 'rm -rf ./* ./.* &>/dev/null'
                sh 'git clone -b dev https://github.com/cloudimix/jenkins_jcasc.git .'
                     }
        }
        stage('Create') {
            steps {
                sh 'uname -a >> myinfo;pwd >> myinfo;whoami >> myinfo'
                sh 'ls -la >> myinfo'
            }
        }
    }
}
