version: '3.3'

services:
  jenkins:
    build:
      context: ./master
#      args:
#        JAVA_OPTS: '-Djenkins.CLI.disabled=true'
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf/jenkins.yaml
volumes:
  jenkins_home:
