jenkins:
  systemMessage: "\n\nHello, Welcome to 'Jenkins CASC Server'..\n\n"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  
 
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: 123456
        - id: ofir
          password: 0000

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  # Enable CSRF
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

  # Enable Slave to Master Access Control
  remotingSecurity:
    enabled: True

# security:
#   remotingCLI:
#     enabled: false
